### ISSUE TITLE
Design question

### ISSUE THREAD

**Issue by harnit-bakshi** [MacHu-GWU/pynamodb_mate-project#1]
Hi,
Thanks for implementing this library I have a question on the general design of this library
Why can we not have a S3Attribute which extends the PynamoDB Attribute
- When we call serialise it should just create and write to S3 first. If successful then create a S3 URI and put it in DynamoDB
- When we call deserialise it should take the S3 URI, download the contents from the S3 bucket/key and then return that value
- We can then extend this attribute for S3BinaryAttribute, S3UnicodeAttribute etc

So was not sure why this approach was not taken instead?

**Comment by harnit-bakshi** [comment]
?

**Comment by MacHu-GWU** [comment]
@harnit-bakshi I am so sorry that I completely forgot the issue page.

Actually you can. the ``pynamodb_mate.Model`` class is just a subclass of original ``pynamodb.models.Model`` class without any change.

But this library aim to provide more feature to the original ``Model``. You can definitely use those S3Backed attributes with the original ``Model``. 

From 2020-2022, I added a lot more attributes and DynamoDB pattern that people can just ``subclass and use``, that's why I created the ``pynamodb_mate.Model`` as the entry point so I can customize it later without changing the import API.
